#Test: scrivere su un file ogni volta che viene fatto un push su questa cartella
name: myFirstCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  push:
    branches:
      - main
      - release/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  firstTest:
    name: myFirstTest
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Avvia Openness
        run: C:/UserData/z004hwns/OneDrive - Siemens AG/Documenti/Benedetta/AAA - Virtual Machine/Shared TIA V18/000 - RepoGitCI/myWorkspace/TestContInt.exe
